### ISSUE TITLE
App is running but nothing happens

### ISSUE THREAD

**Issue by ff6347** [Flave/Isoscope-2.0#3]
The app under http://isoscope-two.fh-potsdam.de/ is running but nothing happens when I click somewhere. :-/ Any ideas what is going wrong?

**Comment by jorditost** [comment]
I had the same problem with my DIGENTI prototypes. HERE has changed the license pricing politics and you need to register a new app.

The good news are that you can register a new app with unlimited timing (but with a limit of 15k queries per month).

**Comment by Flave** [comment]
oh yes. I'll have to check that. thanks for letting me know @fabianmoronzirfas . and thanks for saving me the debugging @jorditost!

**Comment by jorditost** [comment]
Now I'm curious about Isoscope 2.0: @Flave are you using the isochrone service by HERE or by route360 (or both)?

**Comment by ff6347** [comment]
@Flave anything new on  that issue?

**Comment by ff6347** [comment]
fixed
